### ISSUE TITLE
How about a README or 'h' (help) key?

### ISSUE THREAD

**Issue by amitlan** [hlinnaka/pg-internals-explorer#1]
Heikki, :+1: 

I understand you are not particularly serious about this, but I think this looks like an interesting little tool to keep handy. If you get time, could you please add a 'h' (help) key... Or, maybe I can learn me some ncurses. I guess I should fork it.

Thanks anyway!

**Comment by hlinnaka** [comment]
On 01/09/2015 07:12 AM, Amit Langote wrote:

> Heikki, :+1:
> 
> I understand you are not particularly serious about this, but I think
> this looks like an interesting little tool to keep handy. If you get
> time, could you please add a 'h' (help) key... Or, maybe I can learn
> me some ncurses. I guess I should fork it.

That's a good idea. Pull requests are welcome ;-)

The tool really is quite handy - I've used it "for real" when debugging 
b-tree related patches - and I definitely love to improve it whenever I 
get a chance.
- Heikki

**Comment by amitlan** [comment]
Nice! Look forward to it.
